[basic]
vector_size = 300
window = 5
min_count = 1
epoch = 200
workers = 64
prefix_len = 2

bad_api_dir = PreProcess/removed_api_list.txt
WE_proj_name = 0417_final_10000-pkg_c.x
WE_model_name = 0417_final_10000-pkg_c.x
model_name = 0417-random10000_for_corpus_c.x

action = detect
# train or detect


[train]
# needed when action is "train"
pkg_name = Unpackaged_Packages_Example 
proj_name = model_name
dir0 = output_connected.txt
dir1 = output_processing.txt
dir2 = output_simplified.txt
file_search_mode = all_files
# all_files  or setup_only
graph_mode = cfg+cg
# cfg+cg   or  cg
task_num = 64


[detect]
# needed when action is "detect"
dir0 = output_connected_c.x.txt
dir1 = output_processing_c.x.txt
dir2 = output_simplified_c.x.txt
pkg_name = Unpackaged_Packages_1_pypi_tar
proj_name = 1
proj_merged = 1-merged

file_search_mode = setup_only
# all_files  or setup_only
graph_mode = cfg+cg
# cfg+cg   or  cg
rank_mode = p&n
# positive or negative or p&n

min_cluster_size = 2
min_samples = 20
task_num = 64
proj_wait_to_be_merged = final-1_0417_benign_cfg_setup_c.x
negative_proj_name = final-1_0417_malicious_cfg_setup_c.x